[BUILD] cmake: search external dependencies part moved to separate file
pmarusin/3dsoftviz pull request #12
Opened 2017-11-23 10:20 UTC by KrupsonSVK

skuste ci to frci, je umiestnenie noveho cmaku filu ok?

2017-11-23 14:29 UTC, knapikm approved these changes
po oprave funguje

2017-11-24 15:08 UTC, kapecp requested changes
doxygen, sphinx, astyle, cpplint, cppcheck - presunut do samostatnych .cmake suborov

- su to ine veci ako find* skripty, pretoze cez add_custom_target pridavaju nove build target-y

2017-11-29 21:50 UTC, KrupsonSVK commented
nerozumiem, nebolo to vo find* skripte. ak dobre chapem s oddelenim tych add_target do samostatnych cmake, tak napr takto:

_searchDependencies.cmake:_

> option(SKIP_ASTYLE "Skip using Astyle code formatter" OFF)
if (NOT SKIP_ASTYLE)
    find_package(Astyle)
    if (Astyle_FOUND)
        message(STATUS "Astyle FOUND")
        #format souce code
        **include(cmake/astyle.cmake)**        
    endif ()
else ()
    message(STATUS "Skipped using ASTYLE")
endif ()

a _astyle.cmake:_

> add_custom_target("style" COMMAND
        "${ASTYLE_EXECUTABLE}"
        --options=${CMAKE_CURRENT_SOURCE_DIR}/../astyle.options
        ${CMAKE_CURRENT_SOURCE_DIR}/../include/*.h
        ${CMAKE_CURRENT_SOURCE_DIR}/../src/*.cpp
        COMMENT "Formating source code with Astyle."
        VERBATIM
        )

2017-11-29 22:41 UTC, kapecp commented
naco tak komplikovane:
zoberem cely astyle a dam ho do cmake/astyle.cmake a ten includnem v CMakeLists.txt
- takto bude vsetko tykajuce sa astyle na jednom mieste

2017-11-30 09:28 UTC, KrupsonSVK commented
ok spravil som to nejak tak, je to lepsie?

2017-11-30 22:46 UTC, marusinp approved these changes
ok

2017-12-01 13:53 UTC, kapecp requested changes

2017-12-01 13:53 UTC, kapecp commented on CMakeLists.txt
> +# -----Dependencies - Add custom target dependencies----------
lepsi komentar je "Support tools - Add custom build targets"

2017-12-01 13:53 UTC, kapecp commented on cmake/astyle.cmake
> +        add_custom_target("style" COMMAND
treba dorobit podporu pre Windows (Win nezvladne spracovat tento prikaz, lebo je moc dlhy - obmedzenie cmd.exe) 
- vid. format.cmd -> premenovat format.cmd na run_astyle.bat
- riesit podobne ako pre CPPcheck nizsie

2017-12-01 13:53 UTC, kapecp commented on cmake/cppcheck.cmake
> +                    ${CMAKE_CURRENT_SOURCE_DIR}/../run_cppcheck.bat # NOTE: this will probably work only on Linux/OSX
komentar netreba

2017-12-01 13:53 UTC, kapecp commented on cmake/cpplint.cmake
> +                    ${CMAKE_CURRENT_SOURCE_DIR}/../cpplint.bat # NOTE: this will probably work only on Linux/OSX
- premenovat na run_cpplint.bat
- komentar netreba

2017-12-07 09:17 UTC, kapecp approved these changes

2017-12-07 09:30 UTC, merged