[BUILD] cmake: generating lists/groups of sources and headers files moved into separated cmake files
pmarusin/3dsoftviz pull request #13
Opened 2017-11-23 11:18 UTC by knapikm

2017-11-24 15:14 UTC, kapecp requested changes
adresar cmake by mal obsahovat iba:

- find skripty
- pomocne build skripty
- NIE buildovanie 3DSoftviz-u

2017-11-24 15:14 UTC, kapecp commented on CMakeLists.txt
> +include( cmake/Sources.cmake )
toto nie je celkom dobre riesenie:

- presunut cmake/Sources.cmake do src/Sources.cmake
- resp. by sa to malo spravit cez add_subdirectory

2017-11-29 23:29 UTC, KrupsonSVK commented
fixol som to, src/ je ako subdirectory

2017-11-29 23:29 UTC, KrupsonSVK approved these changes

2017-12-01 14:07 UTC, kapecp requested changes
este par drobnosti opravit

2017-12-01 14:07 UTC, kapecp commented on CMakeLists.txt
> +include (cmake/Headers.cmake)
prerobit na `include(include/Headers.cmake)`

2017-12-01 14:07 UTC, kapecp commented on CMakeLists.txt
> +# add cmake module that generates a list of source files
_CMake module_ sa terminologicky pouziva v inom kontexte, resp. znaci nieco ine
- upravit komentar na: _process src directory - get all source files_ (podobne aj nizsie)
- poprosim pisat _CMake_

2017-12-06 20:59 UTC, KrupsonSVK commented
tak co je to ok? 

nemal by byt ten headers.cmake skor ako subdirectory?

2017-12-07 09:21 UTC, kapecp approved these changes

2017-12-07 10:03 UTC, merged