[BUILD] Updated Leap (2.3.1) and Leap-Orion (3.2.1)
pmarusin/3dsoftviz pull request #14
Opened 2017-11-28 12:41 UTC by BLigart

Updated Leap to newest version - 2.3.1 - for all platforms - Windows, Linux, Mac. Also updated Leap-Orion to newest version - 3.2.1 - only for Windows.

2017-11-30 02:48 UTC, marusinp requested changes
edit: problem bol u mna, treba vymazat _build. Vsetko bezi

V module DirectionDetector.h build error - include na riadku 5 hlasi 'Leap.h' not found. Pravdepodobne preto, ze su v projekte dva headre s nazvom Leap.h (Multiple parse contents are available for this file). Asi staci premenovat jeden header alebo zmenit include-y na relative-path/Leap.h (treba premysliet, zajtra mozme pozriet).

2017-11-30 09:03 UTC, marusinp approved these changes

2017-12-01 14:12 UTC, kapecp approved these changes

2017-12-06 20:41 UTC, knapikm approved these changes

2017-12-06 20:49 UTC, KrupsonSVK commented
ide mi to ale mam dve otazky:

42 suborovy commit? rozumiem ze su tam cele cudzie kody ale oddelim aspon tie do samostatneho commitu (bezat vlastny git server tak si ho viem zhodit zobrazenim diffu takehoto dinosaura) 

a preco su tam binarky?

2017-12-06 21:39 UTC, BLigart commented
Áno, dalo by sa to oddeliť, ale tie súbory sú viac menej také isté, išlo len o pridanie súborov pre všetky platformy. Podstata je tá istá: pridaná nová verzia Leapu a Leap-Orionu.
Súbory som pridal len tie, ktoré som zistil zo CMake súboru, že potrebuje projekt k buildu a ktoré tam boli aj pri starej verzii Leapu a Leap-Orionu.

2017-12-06 22:42 UTC, KrupsonSVK approved these changes

2017-12-06 22:44 UTC, merged