[BUILD] added ccache(default OFF) to cmake build
pmarusin/3dsoftviz pull request #17
Opened 2017-11-30 04:04 UTC by KrupsonSVK

funkcny ccache,  pri nadchadzajucom "kodeni" sa uvidi aky to ma efekt

treba dat pozor ci je v systeme v spravnej ceste, je to tam aj okomentovane

2017-12-01 14:21 UTC, kapecp requested changes
OK, ale da sa to spravit aj korektnejsie - vid. http://crascit.com/2016/04/09/using-ccache-with-cmake/

2017-12-04 19:41 UTC, knapikm commented
Sorry, zle som pomenoval commit, je to fixnute

2017-12-04 19:41 UTC, knapikm approved these changes

2017-12-06 11:54 UTC, kapecp approved these changes
az na tie zbytocne 2 prazdne riadky je to OK

2017-12-06 20:11 UTC, merged