[BUILD] cmake external projects moved into subdirectory
pmarusin/3dsoftviz pull request #3
Opened 2017-11-16 07:02 UTC by KrupsonSVK

je to funkcne

2017-11-17 09:35 UTC, knapikm approved these changes

2017-11-20 20:50 UTC, kapecp requested changes
treba drobne upravy
- dodrzat codestyle pre CMake

2017-11-20 20:50 UTC, kapecp commented on dependencies/CMakeLists.txt
> +macro ( build_dependecies _DEP_NAME )
spravnejsi je nazov build_dependency, pretoze sa builduje len jedna dependency

2017-11-20 20:50 UTC, kapecp commented on CMakeLists.txt
> +        add_subdirectory(dependencies)
dodrzat formatovanie zatvoriek, kvoli citatelnosti

2017-11-20 22:17 UTC, KrupsonSVK reviewed
suhlasim (otestovane)

2017-11-20 22:20 UTC, knapikm approved these changes

2017-11-21 12:24 UTC, kapecp approved these changes

2017-11-21 12:33 UTC, merged